
name: Status

on:
  push:
    branches: 
      - master
      - dev

jobs:

  check: 
    runs-on: ubuntu-latest
    outputs:
      isPr: ${{ steps.findPr.outputs.isPr }}
      prNumber: ${{ steps.findPr.outputs.number }}
    steps:
      - uses: actions/checkout@v1
        # Find the PR associated with this push, if there is one.

      - uses: jwalton/gh-find-current-pr@v1
        with:
            # Can be "open", "closed", or "all".  Defaults to "open".
            state: open
        # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - name: "Check if it is a PR"
        id: 
        run: echo "::set-output name=isPr::${{steps.findPr.outputs.number}}"

  test:
    needs: check
    # if: ${{ github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: "echo!"
        run: echo ${{test.needs.check.isPr}} ${{test.needs.check.prNumber}}
      - name: Event Name
        run: echo ${{github.event_name }}
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        # with:
        #   python-version: ${{ matrix.python-version }}
      
      - name: Install system packages
        run: |
          # required for sqlite3 json extension
          sudo apt-get install -y musl-dev
          sudo ln -s /lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
          # install redis server and make sure it is stopped
          sudo apt-get install -y redis-server
          sudo service redis-server stop

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-dev.txt
          pip install flake8 pytest coverage coverage-badge pytest-cov

      - name: Lint with flake8
        id: linter
        run: flake8 . --count --max-complexity=10 --max-line-length=127 

      - name: Test with pytest
        id: tests
        run: | 
          pytest --cov=app --cov-fail-under=60